deploy:
  provider: gae
  keyfile: YOUR SERVICE ACCOUNT JSON FILE
  project: YOUR PROJECT ID
before_install:
- openssl aes-256-cbc -K $encrypted_c4b82e37d806_key -iv $encrypted_c4b82e37d806_iv
  -in api-website-14eb33719b19.json.enc -out api-website-14eb33719b19.json -d
