sudo: required
language: python
python:
  - "2.7"
# Cache our Gcloud SDK between commands
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
# Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_c4b82e37d806_key -iv $encrypted_c4b82e37d806_iv -in api-website-14eb33719b19.json.enc -out api-website-14eb33719b19.json -d
install:
# Set the correct project to deploy to
- gcloud config set project api-website-159123
- gcloud -q components update gae-python
script:
- gcloud deploy --project api-website-159123
