sudo: false
language: python

before_install:
- openssl aes-256-cbc -K $encrypted_c4b82e37d806_key -iv $encrypted_c4b82e37d806_iv -in api-website-14eb33719b19.json.enc -out api-website-14eb33719b19.json -d

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: api-website-14eb33719b19.json
  project: api-website-159123
  on:
    branch: master

install:
- echo "No install requirements.txt"

script:
- echo "No testing main_test.py"
